import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* You can include additional head content here if needed */}
      </head>
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/about">About</Link>
            </li>
            <li>
              <Link href="/contact">Contact</Link>
            </li>
            <li>
              <Link href="/portfolios">Portfolios</Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
        <footer>
          <p>&copy; 2024 My Photography Portfolio</p>
        </footer>
      </body>
    </html>
  );
}
