import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* You can include additional head content here if needed */}
      </head>
      <body>
        <Navbar />
        <main>{children}</main>
        <footer>
          <p>&copy; 2024 My Photography Portfolio</p>
        </footer>
      </body>
    </html>
  );
}
